"""add all

Revision ID: b0547b0fb14d
Revises: f1bc1d4477da
Create Date: 2024-07-30 13:28:44.403171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0547b0fb14d'
down_revision = 'f1bc1d4477da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('captcha_value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'captcha_value')
    # ### end Alembic commands ###
